### ISSUE TITLE
最近是不是联通改了接口，都失效了？

### ISSUE THREAD

**Issue by liuguojun** [tobyxdd/OpenWokuan#2]
以前我家这边加速正常，最近都不能用了。麻烦您有时间看下？

**Comment by tobyxdd** [comment]
我现在用联通宽带机会比较少。。之后考虑用手机版接口重写吧

**Comment by tobyxdd** [comment]
经测接口没变、依然可用。。你什么问题

**Comment by liuguojun** [comment]
的确没问题，我前几天测试的时候本地的网络状态不对，导致提速失败。
ps：帝都联通带宽提速，100m可以提到200m，这个是不是应该有新的提速状态码？

**Comment by luuziiyoo** [comment]
可以用啊 我都写入路由器了  自动提速不需要人工参与

**Comment by tobyxdd** [comment]
提速200M的话 状态码是10吗 按理说我这个能提速到的目标状态码也是从接口获取的 如果联通接口没问题应该也是能兼容100->200的
